version: 1.0
clientapps:
  - name: default
    baseUrl: https://static.facilio.com
    stageBaseUrl: https://static.facilio.com/dev
  - name: new-default
    baseUrl: https://static.facilio.com/newclient
    stageBaseUrl: https://static.facilio.com/dev/newclient
  - name: auth
    baseUrl: https://static.facilio.com/auth
    stageBaseUrl: https://static.facilio.com/dev
  - name: dataloader
    baseUrl: https://static.facilio.com/dataloader
    stageBaseUrl: https://static.facilio.com/dev
  - name: setup
    baseUrl: https://static.facilio.com/setup
    stageBaseUrl: https://static.facilio.com/dev
